"use strict";

const pokemon = [
  'Bulbasaur',
  'Charmander',
  'Squirtle',
  'Caterpie',
  'Weedle',
  'Pidgey',
  'Rattata',
  'Spearow',
  'Ekans',
  'Sandshrew',
  'Vulpix',
  'Zubat',
  'Oddish',
  'Paras',
  'Venonat',
  'Diglett',
  'Meowth',
  'Psyduck',
  'Mankey',
  'Growlithe',
  'Poliwag',
  'Abra',
  'Machop',
  'Bellsprout',
  'Tentacool',
  'Geodude',
  'Ponyta',
  'Slowpoke',
  'Magnemite',
  'Doduo',
  'Seel',
  'Grimer',
  'Shellder',
  'Gastly',
  'Onix',
  'Drowzee',
  'Krabby',
  'Voltorb',
  'Exeggcute',
  'Cubone',
  'Lickitung',
  'Koffing',
  'Rhyhorn',
  'Tangela',
  'Horsea',
  'Goldeen',
  'Staryu',
  'Scyther',
  'Magikarp',
  'Eevee',
  'Porygon',
  'Omanyte',
  'Kabuto',
  'Dratini',
  'Chikorita',
  'Cyndaquil',
  'Totodile',
  'Sentret',
  'Hoothoot',
  'Ledyba',
  'Spinarak',
  'Chinchou',
  'Pichu',
  'Cleffa',
  'Igglybuff',
  'Togepi',
  'Natu',
  'Mareep',
  'Hoppip',
  'Aipom',
  'Sunkern',
  'Yanma',
  'Wooper',
  'Murkrow',
  'Misdreavus',
  'Pineco',
  'Gligar',
  'Snubbull',
  'Sneasel',
  'Teddiursa',
  'Slugma',
  'Swinub',
  'Remoraid',
  'Houndour',
  'Phanpy',
  'Tyrogue',
  'Smoochum',
  'Elekid',
  'Magby',
  'Larvitar',
  'Treecko',
  'Torchic',
  'Mudkip',
  'Poochyena',
  'Zigzagoon',
  'Wurmple',
  'Lotad',
  'Seedot',
  'Taillow',
  'Wingull',
  'Ralts',
  'Surskit',
  'Shroomish',
  'Slakoth',
  'Nincada',
  'Whismur',
  'Makuhita',
  'Azurill',
  'Nosepass',
  'Skitty',
  'Aron',
  'Meditite',
  'Electrike',
  'Gulpin',
  'Carvanha',
  'Wailmer',
  'Numel',
  'Spoink',
  'Trapinch',
  'Cacnea',
  'Swablu',
  'Barboach',
  'Corphish',
  'Baltoy',
  'Lileep',
  'Anorith',
  'Feebas',
  'Shuppet',
  'Duskull',
  'Wynaut',
  'Snorunt',
  'Spheal',
  'Clamperl',
  'Bagon',
  'Beldum',
  'Turtwig',
  'Chimchar',
  'Piplup',
  'Starly',
  'Bidoof',
  'Kricketot',
  'Shinx',
  'Budew',
  'Cranidos',
  'Shieldon',
  'Burmy',
  'Combee',
  'Buizel',
  'Cherubi',
  'Shellos',
  'Drifloon',
  'Buneary',
  'Glameow',
  'Chingling',
  'Stunky',
  'Bronzor',
  'Bonsly',
  'Happiny',
  'Gible',
  'Munchlax',
  'Riolu',
  'Hippopotas',
  'Skorupi',
  'Croagunk',
  'Finneon',
  'Mantyke',
  'Snover',
  'Snivy',
  'Tepig',
  'Oshawott',
  'Patrat',
  'Lillipup',
  'Purrloin',
  'Pansage',
  'Pansear',
  'Panpour',
  'Munna',
  'Pidove',
  'Blitzle',
  'Roggenrola',
  'Woobat',
  'Drilbur',
  'Timburr',
  'Tympole',
  'Sewaddle',
  'Venipede',
  'Cottonee',
  'Petilil',
  'Sandile',
  'Darumaka',
  'Dwebble',
  'Scraggy',
  'Yamask',
  'Tirtouga',
  'Archen',
  'Trubbish',
  'Zorua',
  'Minccino',
  'Gothita',
  'Solosis',
  'Ducklett',
  'Vanillite',
  'Deerling',
  'Karrablast',
  'Foongus',
  'Frillish',
  'Joltik',
  'Ferroseed',
  'Klink',
  'Tynamo',
  'Elgyem',
  'Litwick',
  'Axew',
  'Cubchoo',
  'Shelmet',
  'Mienfoo',
  'Golett',
  'Pawniard',
  'Rufflet',
  'Vullaby',
  'Deino',
  'Larvesta',
  'Chespin',
  'Fennekin',
  'Froakie',
  'Bunnelby',
  'Fletchling',
  'Scatterbug',
  'Litleo',
  'Flabebe',
  'Skiddo',
  'Pancham',
  'Espurr',
  'Honedge',
  'Spritzee',
  'Swirlix',
  'Inkay',
  'Binacle',
  'Skrelp',
  'Clauncher',
  'Helioptile',
  'Tyrunt',
  'Amaura',
  'Goomy',
  'Phantump',
  'Bergmite',
  'Noibat' ];

const randPoke = exports.randPoke = function () {
    let no = Math.floor((Math.random() * 250) + 1);
    return (pokemon[no] ? pokemon[no] : 'Tyrunt'); //I mathed wrong and Tyrunt is cool :D
}

//Now we go into some data which is just here to be easy
const pokenames = exports.pokenames = ["Bulbasaur","Ivysaur","Venusaur","Venusaur-Mega","Charmander","Charmeleon","Charizard","Charizard-Mega-X","Charizard-Mega-Y","Squirtle","Wartortle","Blastoise","Blastoise-Mega","Caterpie","Metapod","Butterfree","Weedle","Kakuna","Beedrill","Beedrill-Mega","Pidgey","Pidgeotto","Pidgeot","Pidgeot-Mega","Rattata","Rattata-Alola","Raticate","Raticate-Alola","Spearow","Fearow","Ekans","Arbok","Pikachu","Pikachu-Cosplay","Pikachu-Rock-Star","Pikachu-Belle","Pikachu-Pop-Star","Pikachu-PhD","Pikachu-Libre","Raichu","Raichu-Alola","Sandshrew","Sandshrew-Alola","Sandslash","Sandslash-Alola","Nidoran-F","Nidorina","Nidoqueen","Nidoran-M","Nidorino","Nidoking","Clefairy","Clefable","Vulpix","Vulpix-Alola","Ninetales","Ninetales-Alola","Jigglypuff","Wigglytuff","Zubat","Golbat","Oddish","Gloom","Vileplume","Paras","Parasect","Venonat","Venomoth","Diglett","Diglett-Alola","Dugtrio","Dugtrio-Alola","Meowth","Meowth-Alola","Persian","Persian-Alola","Psyduck","Golduck","Mankey","Primeape","Growlithe","Arcanine","Poliwag","Poliwhirl","Poliwrath","Abra","Kadabra","Alakazam","Alakazam-Mega","Machop","Machoke","Machamp","Bellsprout","Weepinbell","Victreebel","Tentacool","Tentacruel","Geodude","Geodude-Alola","Graveler","Graveler-Alola","Golem","Golem-Alola","Ponyta","Rapidash","Slowpoke","Slowbro","Slowbro-Mega","Magnemite","Magneton","Farfetch'd","Doduo","Dodrio","Seel","Dewgong","Grimer","Grimer-Alola","Muk","Muk-Alola","Shellder","Cloyster","Gastly","Haunter","Gengar","Gengar-Mega","Onix","Drowzee","Hypno","Krabby","Kingler","Voltorb","Electrode","Exeggcute","Exeggutor","Exeggutor-Alola","Cubone","Marowak","Marowak-Alola","Hitmonlee","Hitmonchan","Lickitung","Koffing","Weezing","Rhyhorn","Rhydon","Chansey","Tangela","Kangaskhan","Kangaskhan-Mega","Horsea","Seadra","Goldeen","Seaking","Staryu","Starmie","Mr. Mime","Scyther","Jynx","Electabuzz","Magmar","Pinsir","Pinsir-Mega","Tauros","Magikarp","Gyarados","Gyarados-Mega","Lapras","Ditto","Eevee","Vaporeon","Jolteon","Flareon","Porygon","Omanyte","Omastar","Kabuto","Kabutops","Aerodactyl","Aerodactyl-Mega","Snorlax","Articuno","Zapdos","Moltres","Dratini","Dragonair","Dragonite","Mewtwo","Mewtwo-Mega-X","Mewtwo-Mega-Y","Mew","Chikorita","Bayleef","Meganium","Cyndaquil","Quilava","Typhlosion","Totodile","Croconaw","Feraligatr","Sentret","Furret","Hoothoot","Noctowl","Ledyba","Ledian","Spinarak","Ariados","Crobat","Chinchou","Lanturn","Pichu","Pichu-Spiky-eared","Cleffa","Igglybuff","Togepi","Togetic","Natu","Xatu","Mareep","Flaaffy","Ampharos","Ampharos-Mega","Bellossom","Marill","Azumarill","Sudowoodo","Politoed","Hoppip","Skiploom","Jumpluff","Aipom","Sunkern","Sunflora","Yanma","Wooper","Quagsire","Espeon","Umbreon","Murkrow","Slowking","Misdreavus","Unown","Wobbuffet","Girafarig","Pineco","Forretress","Dunsparce","Gligar","Steelix","Steelix-Mega","Snubbull","Granbull","Qwilfish","Scizor","Scizor-Mega","Shuckle","Heracross","Heracross-Mega","Sneasel","Teddiursa","Ursaring","Slugma","Magcargo","Swinub","Piloswine","Corsola","Remoraid","Octillery","Delibird","Mantine","Skarmory","Houndour","Houndoom","Houndoom-Mega","Kingdra","Phanpy","Donphan","Porygon2","Stantler","Smeargle","Tyrogue","Hitmontop","Smoochum","Elekid","Magby","Miltank","Blissey","Raikou","Entei","Suicune","Larvitar","Pupitar","Tyranitar","Tyranitar-Mega","Lugia","Ho-Oh","Celebi","Treecko","Grovyle","Sceptile","Sceptile-Mega","Torchic","Combusken","Blaziken","Blaziken-Mega","Mudkip","Marshtomp","Swampert","Swampert-Mega","Poochyena","Mightyena","Zigzagoon","Linoone","Wurmple","Silcoon","Beautifly","Cascoon","Dustox","Lotad","Lombre","Ludicolo","Seedot","Nuzleaf","Shiftry","Taillow","Swellow","Wingull","Pelipper","Ralts","Kirlia","Gardevoir","Gardevoir-Mega","Surskit","Masquerain","Shroomish","Breloom","Slakoth","Vigoroth","Slaking","Nincada","Ninjask","Shedinja","Whismur","Loudred","Exploud","Makuhita","Hariyama","Azurill","Nosepass","Skitty","Delcatty","Sableye","Sableye-Mega","Mawile","Mawile-Mega","Aron","Lairon","Aggron","Aggron-Mega","Meditite","Medicham","Medicham-Mega","Electrike","Manectric","Manectric-Mega","Plusle","Minun","Volbeat","Illumise","Roselia","Gulpin","Swalot","Carvanha","Sharpedo","Sharpedo-Mega","Wailmer","Wailord","Numel","Camerupt","Camerupt-Mega","Torkoal","Spoink","Grumpig","Spinda","Trapinch","Vibrava","Flygon","Cacnea","Cacturne","Swablu","Altaria","Altaria-Mega","Zangoose","Seviper","Lunatone","Solrock","Barboach","Whiscash","Corphish","Crawdaunt","Baltoy","Claydol","Lileep","Cradily","Anorith","Armaldo","Feebas","Milotic","Castform","Castform-Sunny","Castform-Rainy","Castform-Snowy","Kecleon","Shuppet","Banette","Banette-Mega","Duskull","Dusclops","Tropius","Chimecho","Absol","Absol-Mega","Wynaut","Snorunt","Glalie","Glalie-Mega","Spheal","Sealeo","Walrein","Clamperl","Huntail","Gorebyss","Relicanth","Luvdisc","Bagon","Shelgon","Salamence","Salamence-Mega","Beldum","Metang","Metagross","Metagross-Mega","Regirock","Regice","Registeel","Latias","Latias-Mega","Latios","Latios-Mega","Kyogre","Kyogre-Primal","Groudon","Groudon-Primal","Rayquaza","Rayquaza-Mega","Jirachi","Deoxys","Deoxys-Attack","Deoxys-Defense","Deoxys-Speed","Turtwig","Grotle","Torterra","Chimchar","Monferno","Infernape","Piplup","Prinplup","Empoleon","Starly","Staravia","Staraptor","Bidoof","Bibarel","Kricketot","Kricketune","Shinx","Luxio","Luxray","Budew","Roserade","Cranidos","Rampardos","Shieldon","Bastiodon","Burmy","Wormadam","Wormadam-Sandy","Wormadam-Trash","Mothim","Combee","Vespiquen","Pachirisu","Buizel","Floatzel","Cherubi","Cherrim","Cherrim-Sunshine","Shellos","Gastrodon","Ambipom","Drifloon","Drifblim","Buneary","Lopunny","Lopunny-Mega","Mismagius","Honchkrow","Glameow","Purugly","Chingling","Stunky","Skuntank","Bronzor","Bronzong","Bonsly","Mime Jr.","Happiny","Chatot","Spiritomb","Gible","Gabite","Garchomp","Garchomp-Mega","Munchlax","Riolu","Lucario","Lucario-Mega","Hippopotas","Hippowdon","Skorupi","Drapion","Croagunk","Toxicroak","Carnivine","Finneon","Lumineon","Mantyke","Snover","Abomasnow","Abomasnow-Mega","Weavile","Magnezone","Lickilicky","Rhyperior","Tangrowth","Electivire","Magmortar","Togekiss","Yanmega","Leafeon","Glaceon","Gliscor","Mamoswine","Porygon-Z","Gallade","Gallade-Mega","Probopass","Dusknoir","Froslass","Rotom","Rotom-Heat","Rotom-Wash","Rotom-Frost","Rotom-Fan","Rotom-Mow","Uxie","Mesprit","Azelf","Dialga","Palkia","Heatran","Regigigas","Giratina","Giratina-Origin","Cresselia","Phione","Manaphy","Darkrai","Shaymin","Shaymin-Sky","Arceus","Arceus-Bug","Arceus-Dark","Arceus-Dragon","Arceus-Electric","Arceus-Fairy","Arceus-Fighting","Arceus-Fire","Arceus-Flying","Arceus-Ghost","Arceus-Grass","Arceus-Ground","Arceus-Ice","Arceus-Poison","Arceus-Psychic","Arceus-Rock","Arceus-Steel","Arceus-Water","Victini","Snivy","Servine","Serperior","Tepig","Pignite","Emboar","Oshawott","Dewott","Samurott","Patrat","Watchog","Lillipup","Herdier","Stoutland","Purrloin","Liepard","Pansage","Simisage","Pansear","Simisear","Panpour","Simipour","Munna","Musharna","Pidove","Tranquill","Unfezant","Blitzle","Zebstrika","Roggenrola","Boldore","Gigalith","Woobat","Swoobat","Drilbur","Excadrill","Audino","Audino-Mega","Timburr","Gurdurr","Conkeldurr","Tympole","Palpitoad","Seismitoad","Throh","Sawk","Sewaddle","Swadloon","Leavanny","Venipede","Whirlipede","Scolipede","Cottonee","Whimsicott","Petilil","Lilligant","Basculin","Basculin-Blue-Striped","Sandile","Krokorok","Krookodile","Darumaka","Darmanitan","Darmanitan-Zen","Maractus","Dwebble","Crustle","Scraggy","Scrafty","Sigilyph","Yamask","Cofagrigus","Tirtouga","Carracosta","Archen","Archeops","Trubbish","Garbodor","Zorua","Zoroark","Minccino","Cinccino","Gothita","Gothorita","Gothitelle","Solosis","Duosion","Reuniclus","Ducklett","Swanna","Vanillite","Vanillish","Vanilluxe","Deerling","Sawsbuck","Emolga","Karrablast","Escavalier","Foongus","Amoonguss","Frillish","Jellicent","Alomomola","Joltik","Galvantula","Ferroseed","Ferrothorn","Klink","Klang","Klinklang","Tynamo","Eelektrik","Eelektross","Elgyem","Beheeyem","Litwick","Lampent","Chandelure","Axew","Fraxure","Haxorus","Cubchoo","Beartic","Cryogonal","Shelmet","Accelgor","Stunfisk","Mienfoo","Mienshao","Druddigon","Golett","Golurk","Pawniard","Bisharp","Bouffalant","Rufflet","Braviary","Vullaby","Mandibuzz","Heatmor","Durant","Deino","Zweilous","Hydreigon","Larvesta","Volcarona","Cobalion","Terrakion","Virizion","Tornadus","Tornadus-Therian","Thundurus","Thundurus-Therian","Reshiram","Zekrom","Landorus","Landorus-Therian","Kyurem","Kyurem-Black","Kyurem-White","Keldeo","Keldeo-Resolute","Meloetta","Meloetta-Pirouette","Genesect","Genesect-Douse","Genesect-Shock","Genesect-Burn","Genesect-Chill","Chespin","Quilladin","Chesnaught","Fennekin","Braixen","Delphox","Froakie","Frogadier","Greninja","Greninja-Ash","Bunnelby","Diggersby","Fletchling","Fletchinder","Talonflame","Scatterbug","Spewpa","Vivillon","Vivillon-Fancy","Vivillon-Pokeball","Litleo","Pyroar","Flabebe","Floette","Floette-Eternal","Florges","Skiddo","Gogoat","Pancham","Pangoro","Furfrou","Espurr","Meowstic","Meowstic-F","Honedge","Doublade","Aegislash","Aegislash-Blade","Spritzee","Aromatisse","Swirlix","Slurpuff","Inkay","Malamar","Binacle","Barbaracle","Skrelp","Dragalge","Clauncher","Clawitzer","Helioptile","Heliolisk","Tyrunt","Tyrantrum","Amaura","Aurorus","Sylveon","Hawlucha","Dedenne","Carbink","Goomy","Sliggoo","Goodra","Klefki","Phantump","Trevenant","Pumpkaboo","Pumpkaboo-Small","Pumpkaboo-Large","Pumpkaboo-Super","Gourgeist","Gourgeist-Small","Gourgeist-Large","Gourgeist-Super","Bergmite","Avalugg","Noibat","Noivern","Xerneas","Yveltal","Zygarde","Zygarde-10%","Zygarde-Complete","Diancie","Diancie-Mega","Hoopa","Hoopa-Unbound","Volcanion","Rowlet","Dartrix","Decidueye","Litten","Torracat","Incineroar","Popplio","Brionne","Primarina","Pikipek","Trumbeak","Toucannon","Yungoos","Gumshoos","Grubbin","Charjabug","Vikavolt","Crabrawler","Crabominable","Oricorio","Oricorio-Pom-Pom","Oricorio-Pa'u","Oricorio-Sensu","Cutiefly","Ribombee","Rockruff","Lycanroc","Lycanroc-Midnight","Wishiwashi","Wishiwashi-School","Mareanie","Toxapex","Mudbray","Mudsdale","Dewpider","Araquanid","Fomantis","Lurantis","Morelull","Shiinotic","Salandit","Salazzle","Stufful","Bewear","Bounsweet","Steenee","Tsareena","Comfey","Oranguru","Passimian","Wimpod","Golisopod","Sandygast","Palossand","Pyukumuku","Type: Null","Silvally","Silvally-Bug","Silvally-Dark","Silvally-Dragon","Silvally-Electric","Silvally-Fairy","Silvally-Fighting","Silvally-Fire","Silvally-Flying","Silvally-Ghost","Silvally-Grass","Silvally-Ground","Silvally-Ice","Silvally-Poison","Silvally-Psychic","Silvally-Rock","Silvally-Steel","Silvally-Water","Minior","Minior-Meteor","Komala","Turtonator","Togedemaru","Mimikyu","Mimikyu-Busted","Bruxish","Drampa","Dhelmise","Jangmo-o","Hakamo-o","Kommo-o","Tapu Koko","Tapu Lele","Tapu Bulu","Tapu Fini","Cosmog","Cosmoem","Solgaleo","Lunala","Nihilego","Buzzwole","Pheromosa","Xurkitree","Celesteela","Kartana","Guzzlord","Necrozma","Magearna","Marshadow","Missingno.","Tomohawk","Necturna","Mollux","Aurumoth","Malaconda","Cawmodore","Volkraken","Plasmanta","Naviathan","Crucibelle","Crucibelle-Mega","Kerfluffle","Syclant","Revenankh","Pyroak","Fidgit","Stratagem","Arghonaut","Kitsunoh","Cyclohm","Colossoil","Krilowatt","Voodoom"]
const items = exports.items = ["Abomasite","Absolite","Absorb Bulb","Adamant Orb","Adrenaline Orb","Aerodactylite","Aggronite","Aguav Berry","Air Balloon","Alakazite","Aloraichium Z","Altarianite","Ampharosite","Apicot Berry","Armor Fossil","Aspear Berry","Assault Vest","Audinite","Babiri Berry","Banettite","Beast Ball","Beedrillite","Belue Berry","Berry Juice","Big Root","Binding Band","Black Belt","Black Sludge","Black Glasses","Blastoisinite","Blazikenite","Blue Orb","Bluk Berry","BrightPowder","Bug Gem","Bug Memory","Buginium Z","Burn Drive","Cameruptite","Cell Battery","Charcoal","Charizardite X","Charizardite Y","Charti Berry","Cheri Berry","Cherish Ball","Chesto Berry","Chilan Berry","Chill Drive","Choice Band","Choice Scarf","Choice Specs","Chople Berry","Claw Fossil","Coba Berry","Colbur Berry","Cornn Berry","Cover Fossil","Custap Berry","Damp Rock","Dark Gem","Dark Memory","Darkinium Z","Decidium Z","DeepSeaScale","DeepSeaTooth","Destiny Knot","Diancite","Dive Ball","Dome Fossil","Douse Drive","Draco Plate","Dragon Fang","Dragon Gem","Dragon Memory","Dragonium Z","Dread Plate","Dream Ball","Durin Berry","Dusk Ball","Earth Plate","Eevium Z","Eject Button","Electirizer","Electric Gem","Electric Memory","Electric Seed","Electrium Z","Energy Powder","Enigma Berry","Eviolite","Expert Belt","Fairium Z","Fairy Gem","Fairy Memory","Fast Ball","Fighting Gem","Fighting Memory","Fightinium Z","Figy Berry","Fire Gem","Fire Memory","Firium Z","Fist Plate","Flame Orb","Flame Plate","Float Stone","Flying Gem","Flying Memory","Flyinium Z","Focus Band","Focus Sash","Friend Ball","Full Incense","Galladite","Ganlon Berry","Garchompite","Gardevoirite","Gengarite","Ghost Gem","Ghost Memory","Ghostium Z","Glalitite","Grass Gem","Grass Memory","Grassium Z","Grassy Seed","Great Ball","Grepa Berry","Grip Claw","Griseous Orb","Ground Gem","Ground Memory","Groundium Z","Gyaradosite","Haban Berry","Hard Stone","Heal Ball","Heat Rock","Heavy Ball","Helix Fossil","Heracronite","Hondew Berry","Houndoominite","Iapapa Berry","Ice Gem","Ice Memory","Icicle Plate","Icium Z","Icy Rock","Incinium Z","Insect Plate","Iron Ball","Iron Plate","Jaboca Berry","Kasib Berry","Kebia Berry","Kee Berry","Kelpsy Berry","Kangaskhanite","King's Rock","Lagging Tail","Lansat Berry","Latiasite","Latiosite","Lax Incense","Leftovers","Leppa Berry","Level Ball","Liechi Berry","Life Orb","Light Ball","Light Clay","Lopunnite","Love Ball","Lucarionite","Lucky Punch","Lum Berry","Luminous Moss","Lure Ball","Lustrous Orb","Luxury Ball","Macho Brace","Magnet","Mago Berry","Magost Berry","Mail","Manectite","Maranga Berry","Marshadium Z","Master Ball","Mawilite","Meadow Plate","Medichamite","Mental Herb","Metagrossite","Metal Coat","Metal Powder","Metronome","Mewnium Z","Mewtwonite X","Mewtwonite Y","Micle Berry","Mind Plate","Miracle Seed","Misty Seed","Moon Ball","Muscle Band","Mystic Water","Nanab Berry","Nest Ball","Net Ball","Never-Melt Ice","Nomel Berry","Normal Gem","Normalium Z","Occa Berry","Odd Incense","Old Amber","Oran Berry","Pamtre Berry","Park Ball","Passho Berry","Payapa Berry","Pecha Berry","Persim Berry","Petaya Berry","Pidgeotite","Pikanium Z","Pikashunium Z","Pinap Berry","Pinsirite","Pixie Plate","Plume Fossil","Poison Barb","Poison Gem","Poison Memory","Poisonium Z","Poke Ball","Pomeg Berry","Power Herb","Premier Ball","Primarium Z","Protective Pads","Psychic Gem","Psychic Memory","Psychic Seed","Psychium Z","Qualot Berry","Quick Ball","Quick Claw","Quick Powder","Rabuta Berry","Rare Bone","Rawst Berry","Razor Claw","Razor Fang","Razz Berry","Red Card","Red Orb","Repeat Ball","Rindo Berry","Ring Target","Rock Gem","Rock Incense","Rock Memory","Rockium Z","Rocky Helmet","Root Fossil","Rose Incense","Roseli Berry","Rowap Berry","Sablenite","Safari Ball","Safety Goggles","Salac Berry","Salamencite","Sceptilite","Scizorite","Scope Lens","Sea Incense","Sharp Beak","Sharpedonite","Shed Shell","Shell Bell","Shock Drive","Shuca Berry","Silk Scarf","SilverPowder","Sitrus Berry","Skull Fossil","Sky Plate","Slowbronite","Smooth Rock","Snorlium Z","Snowball","Soft Sand","Soul Dew","Spell Tag","Spelon Berry","Splash Plate","Spooky Plate","Sport Ball","Starf Berry","Steelixite","Steel Gem","Steel Memory","Steelium Z","Stick","Sticky Barb","Stone Plate","Swampertite","Tamato Berry","Tanga Berry","Tapunium Z","Terrain Extender","Thick Club","Timer Ball","Toxic Orb","Toxic Plate","TwistedSpoon","Tyranitarite","Ultra Ball","Venusaurite","Wacan Berry","Water Gem","Water Memory","Waterium Z","Watmel Berry","Wave Incense","Weakness Policy","Wepear Berry","White Herb","Wide Lens","Wiki Berry","Wise Glasses","Yache Berry","Zap Plate","Zoom Lens","Berserk Gene","Berry","Bitter Berry","Burnt Berry","Dragon Scale","Gold Berry","Ice Berry","Mint Berry","Miracle Berry","Mystery Berry","Pink Bow","Polkadot Bow","PRZ Cure Berry","PSN Cure Berry","Crucibellite"];
const abilities = exports.abilities = ["Adaptability","Aftermath","Aerilate","Air Lock","Analytic","Anger Point","Anticipation","Arena Trap","Aroma Veil","Aura Break","Bad Dreams","Battery","Battle Armor","Battle Bond","Beast Boost","Berserk","Big Pecks","Blaze","Bulletproof","Cheek Pouch","Chlorophyll","Clear Body","Cloud Nine","Color Change","Comatose","Competitive","Compound Eyes","Contrary","Corrosion","Cursed Body","Cute Charm","Damp","Dancer","Dark Aura","Dazzling","Defeatist","Defiant","Delta Stream","Desolate Land","Disguise","Download","Drizzle","Drought","Dry Skin","Early Bird","Effect Spore","Electric Surge","Emergency Exit","Fairy Aura","Filter","Flame Body","Flare Boost","Flash Fire","Flower Gift","Flower Veil","Fluffy","Forecast","Forewarn","Friend Guard","Frisk","Full Metal Body","Fur Coat","Gale Wings","Galvanize","Gluttony","Gooey","Grass Pelt","Grassy Surge","Guts","Harvest","Healer","Heatproof","Heavy Metal","Honey Gather","Huge Power","Hustle","Hydration","Hyper Cutter","Ice Body","Illuminate","Illusion","Immunity","Imposter","Infiltrator","Innards Out","Inner Focus","Insomnia","Intimidate","Iron Barbs","Iron Fist","Justified","Keen Eye","Klutz","Leaf Guard","Levitate","Light Metal","Lightning Rod","Limber","Liquid Ooze","Liquid Voice","Long Reach","Magic Bounce","Magic Guard","Magician","Magma Armor","Magnet Pull","Marvel Scale","Mega Launcher","Merciless","Minus","Misty Surge","Mold Breaker","Moody","Motor Drive","Moxie","Multiscale","Multitype","Mummy","Natural Cure","No Guard","Normalize","Oblivious","Overcoat","Overgrow","Own Tempo","Parental Bond","Pickup","Pickpocket","Pixilate","Plus","Poison Heal","Poison Point","Poison Touch","Power Construct","Power of Alchemy","Prankster","Pressure","Primordial Sea","Prism Armor","Protean","Psychic Surge","Pure Power","Queenly Majesty","Quick Feet","Rain Dish","Rattled","Receiver","Reckless","Refrigerate","Regenerator","Rivalry","RKS System","Rock Head","Rough Skin","Run Away","Sand Force","Sand Rush","Sand Stream","Sand Veil","Sap Sipper","Schooling","Scrappy","Serene Grace","Shadow Shield","Shadow Tag","Shed Skin","Sheer Force","Shell Armor","Shield Dust","Shields Down","Simple","Skill Link","Slow Start","Slush Rush","Sniper","Snow Cloak","Snow Warning","Solar Power","Solid Rock","Soul-Heart","Soundproof","Speed Boost","Stakeout","Stall","Stamina","Stance Change","Static","Steadfast","Steelworker","Stench","Sticky Hold","Storm Drain","Strong Jaw","Sturdy","Suction Cups","Super Luck","Surge Surfer","Swarm","Sweet Veil","Swift Swim","Symbiosis","Synchronize","Tangled Feet","Tangling Hair","Technician","Telepathy","Teravolt","Thick Fat","Tinted Lens","Torrent","Toxic Boost","Tough Claws","Trace","Triage","Truant","Turboblaze","Unaware","Unburden","Unnerve","Victory Star","Vital Spirit","Volt Absorb","Water Absorb","Water Bubble","Water Compaction","Water Veil","Weak Armor","White Smoke","Wimp Out","Wonder Guard","Wonder Skin","Zen Mode","Mountaineer","Rebound","Persistent"];
const moves = exports.moves = ["10,000,000 Volt Thunderbolt","Absorb","Accelerock","Acid","Acid Armor","Acid Downpour","Acid Spray","Acrobatics","Acupressure","Aerial Ace","Aeroblast","After You","Agility","Air Cutter","Air Slash","All-Out Pummeling","Ally Switch","Amnesia","Anchor Shot","Ancient Power","Aqua Jet","Aqua Ring","Aqua Tail","Arm Thrust","Aromatherapy","Aromatic Mist","Assist","Assurance","Astonish","Attack Order","Attract","Aura Sphere","Aurora Beam","Aurora Veil","Autotomize","Avalanche","Baby-Doll Eyes","Baneful Bunker","Barrage","Barrier","Baton Pass","Beak Blast","Beat Up","Belch","Belly Drum","Bestow","Bide","Bind","Bite","Black Hole Eclipse","Blast Burn","Blaze Kick","Blizzard","Block","Bloom Doom","Blue Flare","Body Slam","Bolt Strike","Bone Club","Bone Rush","Bonemerang","Boomburst","Bounce","Brave Bird","Breakneck Blitz","Brick Break","Brine","Brutal Swing","Bubble","Bubble Beam","Bug Bite","Bug Buzz","Bulk Up","Bulldoze","Bullet Punch","Bullet Seed","Burn Up","Calm Mind","Camouflage","Captivate","Catastropika","Celebrate","Charge","Charge Beam","Charm","Chatter","Chip Away","Circle Throw","Clamp","Clanging Scales","Clear Smog","Close Combat","Coil","Comet Punch","Confide","Confuse Ray","Confusion","Constrict","Continental Crush","Conversion","Conversion 2","Copycat","Core Enforcer","Corkscrew Crash","Cosmic Power","Cotton Guard","Cotton Spore","Counter","Covet","Crabhammer","Crafty Shield","Cross Chop","Cross Poison","Crunch","Crush Claw","Crush Grip","Curse","Cut","Dark Pulse","Dark Void","Darkest Lariat","Dazzling Gleam","Defend Order","Defense Curl","Defog","Destiny Bond","Detect","Devastating Drake","Diamond Storm","Dig","Disable","Disarming Voice","Discharge","Dive","Dizzy Punch","Doom Desire","Double-Edge","Double Hit","Double Kick","Double Slap","Double Team","Draco Meteor","Dragon Ascent","Dragon Breath","Dragon Claw","Dragon Dance","Dragon Hammer","Dragon Pulse","Dragon Rage","Dragon Rush","Dragon Tail","Draining Kiss","Drain Punch","Dream Eater","Drill Peck","Drill Run","Dual Chop","Dynamic Punch","Earth Power","Earthquake","Echoed Voice","Eerie Impulse","Egg Bomb","Electric Terrain","Electrify","Electro Ball","Electroweb","Embargo","Ember","Encore","Endeavor","Endure","Energy Ball","Entrainment","Eruption","Explosion","Extrasensory","Extreme Evoboost","Extreme Speed","Facade","Feint Attack","Fairy Lock","Fairy Wind","Fake Out","Fake Tears","False Swipe","Feather Dance","Feint","Fell Stinger","Fiery Dance","Final Gambit","Fire Blast","Fire Fang","Fire Lash","Fire Pledge","Fire Punch","Fire Spin","First Impression","Fissure","Flail","Flame Burst","Flame Charge","Flame Wheel","Flamethrower","Flare Blitz","Flash","Flash Cannon","Flatter","Fleur Cannon","Fling","Floral Healing","Flower Shield","Fly","Flying Press","Focus Blast","Focus Energy","Focus Punch","Follow Me","Force Palm","Foresight","Forest's Curse","Foul Play","Freeze-Dry","Freeze Shock","Frenzy Plant","Frost Breath","Frustration","Fury Attack","Fury Cutter","Fury Swipes","Fusion Bolt","Fusion Flare","Future Sight","Gastro Acid","Gear Grind","Gear Up","Genesis Supernova","Geomancy","Giga Drain","Giga Impact","Gigavolt Havoc","Glaciate","Glare","Grass Knot","Grass Pledge","Grass Whistle","Grassy Terrain","Gravity","Growl","Growth","Grudge","Guard Split","Guard Swap","Guardian of Alola","Guillotine","Gunk Shot","Gust","Gyro Ball","Hail","Hammer Arm","Happy Hour","Harden","Haze","Head Charge","Head Smash","Headbutt","Heal Bell","Heal Block","Heal Order","Heal Pulse","Healing Wish","Heart Stamp","Heart Swap","Heat Crash","Heat Wave","Heavy Slam","Helping Hand","Hex", "Hidden Power", "Hidden Power Fire", "Hidden Power Water", "Hidden Power Grass", "Hidden Power Electric", "Hidden Power Fighting", "Hidden Power Flying", "Hidden Power Fairy", "Hidden Power Ice", "Hidden Power Poison", "Hidden Power Ghost", "Hidden Power Psychic", "Hidden Power Dark", "Hidden Power Steel", "Hidden Power Rock", "Hidden Power Ground", "Hidden Power Bug", "Hidden Power Dragon", "Hidden Power Bug","Hidden Power Dark","Hidden Power Dragon","Hidden Power Electric","Hidden Power Fighting","Hidden Power Fire","Hidden Power Flying","Hidden Power Ghost","Hidden Power Grass","Hidden Power Ground","Hidden Power Ice","Hidden Power Poison","Hidden Power Psychic","Hidden Power Rock","Hidden Power Steel","Hidden Power Water","High Horsepower","High Jump Kick","Hold Back","Hold Hands","Hone Claws","Horn Attack","Horn Drill","Horn Leech","Howl","Hurricane","Hydro Cannon","Hydro Pump","Hydro Vortex","Hyper Beam","Hyper Fang","Hyperspace Fury","Hyperspace Hole","Hyper Voice","Hypnosis","Ice Ball","Ice Beam","Ice Burn","Ice Fang","Ice Hammer","Ice Punch","Ice Shard","Icicle Crash","Icicle Spear","Icy Wind","Imprison","Incinerate","Inferno","Inferno Overdrive","Infestation","Ingrain","Instruct","Ion Deluge","Iron Defense","Iron Head","Iron Tail","Judgment","Jump Kick","Karate Chop","Kinesis","King's Shield","Knock Off","Land's Wrath","Laser Focus","Last Resort","Lava Plume","Leaf Blade","Leaf Storm","Leaf Tornado","Leafage","Leech Life","Leech Seed","Leer","Lick","Light of Ruin","Light Screen","Liquidation","Lock-On","Lovely Kiss","Low Kick","Low Sweep","Lucky Chant","Lunar Dance","Lunge","Luster Purge","Mach Punch","Magic Coat","Magic Room","Magical Leaf","Magma Storm","Magnet Bomb","Magnetic Flux","Magnet Rise","Magnitude","Malicious Moonsault","Mat Block","Me First","Mean Look","Meditate","Mega Drain","Mega Kick","Mega Punch","Megahorn","Memento","Metal Burst","Metal Claw","Metal Sound","Meteor Mash","Metronome","Milk Drink","Mimic","Mind Reader","Minimize","Miracle Eye","Mirror Coat","Mirror Move","Mirror Shot","Mist","Mist Ball","Misty Terrain","Moonblast","Moongeist Beam","Moonlight","Morning Sun","Mud-Slap","Mud Bomb","Mud Shot","Mud Sport","Muddy Water","Multi-Attack","Mystical Fire","Nasty Plot","Natural Gift","Nature Power","Nature's Madness","Needle Arm","Never-Ending Nightmare","Night Daze","Night Shade","Night Slash","Nightmare","Noble Roar","Nuzzle","Oblivion Wing","Oceanic Operetta","Octazooka","Odor Sleuth","Ominous Wind","Origin Pulse","Outrage","Overheat","Pain Split","Parabolic Charge","Parting Shot","Pay Day","Payback","Peck","Perish Song","Petal Blizzard","Petal Dance","Phantom Force","Pin Missile","Play Nice","Play Rough","Pluck","Poison Fang","Poison Gas","Poison Jab","Poison Powder","Poison Sting","Poison Tail","Pollen Puff","Pound","Powder","Powder Snow","Power Gem","Power Split","Power Swap","Power Trick","Power Trip","Power-Up Punch","Power Whip","Precipice Blades","Present","Prismatic Laser","Protect","Psybeam","Psych Up","Psychic","Psychic Fangs","Psychic Terrain","Psycho Boost","Psycho Cut","Psycho Shift","Psyshock","Psystrike","Psywave","Pulverizing Pancake","Punishment","Purify","Pursuit","Quash","Quick Attack","Quick Guard","Quiver Dance","Rage","Rage Powder","Rain Dance","Rapid Spin","Razor Leaf","Razor Shell","Razor Wind","Recover","Recycle","Reflect","Reflect Type","Refresh","Relic Song","Rest","Retaliate","Return","Revelation Dance","Revenge","Reversal","Roar","Roar of Time","Rock Blast","Rock Climb","Rock Polish","Rock Slide","Rock Smash","Rock Throw","Rock Tomb","Rock Wrecker","Role Play","Rolling Kick","Rollout","Roost","Rototiller","Round","Sacred Fire","Sacred Sword","Safeguard","Sand Attack","Sand Tomb","Sandstorm","Savage Spin-Out","Scald","Scary Face","Scratch","Screech","Searing Shot","Secret Power","Secret Sword","Seed Bomb","Seed Flare","Seismic Toss","Self-Destruct","Shadow Ball","Shadow Bone","Shadow Claw","Shadow Force","Shadow Punch","Shadow Sneak","Sharpen","Shattered Psyche","Sheer Cold","Shell Smash","Shell Trap","Shift Gear","Shock Wave","Shore Up","Signal Beam","Silver Wind","Simple Beam","Sing","Sinister Arrow Raid","Sketch","Skill Swap","Skull Bash","Sky Attack","Sky Drop","Sky Uppercut","Slack Off","Slam","Slash","Sleep Powder","Sleep Talk","Sludge","Sludge Bomb","Sludge Wave","Smack Down","Smart Strike","Smelling Salts","Smog","Smokescreen","Snarl","Snatch","Snore","Spectral Thief","Speed Swap","Spiky Shield","Spirit Shackle","Soak","Soft-Boiled","Solar Beam","Solar Blade","Sonic Boom","Soul-Stealing 7-Star Strike","Spacial Rend","Spark","Sparkling Aria","Spider Web","Spike Cannon","Spikes","Spit Up","Spite","Splash","Spore","Spotlight","Stealth Rock","Steam Eruption","Steel Wing","Sticky Web","Stockpile","Stoked Sparksurfer","Stomp","Stomping Tantrum","Stone Edge","Stored Power","Storm Throw","Steamroller","Strength","Strength Sap","String Shot","Struggle","Struggle Bug","Stun Spore","Submission","Substitute","Subzero Slammer","Sucker Punch","Sunny Day","Sunsteel Strike","Super Fang","Superpower","Supersonic","Supersonic Skystrike","Surf","Swagger","Swallow","Sweet Kiss","Sweet Scent","Swift","Switcheroo","Swords Dance","Synchronoise","Synthesis","Tackle","Tail Glow","Tail Slap","Tail Whip","Tailwind","Take Down","Taunt","Tearful Look","Techno Blast","Tectonic Rage","Teeter Dance","Telekinesis","Teleport","Thief","Thousand Arrows","Thousand Waves","Thrash","Throat Chop","Thunder","Thunder Fang","Thunder Punch","Thunder Shock","Thunder Wave","Thunderbolt","Tickle","Topsy-Turvy","Torment","Toxic","Toxic Spikes","Toxic Thread","Transform","Tri Attack","Trick","Trick-or-Treat","Trick Room","Triple Kick","Trop Kick","Trump Card","Twineedle","Twinkle Tackle","Twister","U-turn","Uproar","V-create","Vacuum Wave","Venom Drench","Venoshock","Vice Grip","Vine Whip","Vital Throw","Volt Switch","Volt Tackle","Wake-Up Slap","Water Gun","Water Pledge","Water Pulse","Water Sport","Water Spout","Waterfall","Water Shuriken","Weather Ball","Whirlpool","Whirlwind","Wide Guard","Wild Charge","Will-O-Wisp","Wing Attack","Wish","Withdraw","Wonder Room","Wood Hammer","Work Up","Worry Seed","Wrap","Wring Out","X-Scissor","Yawn","Zap Cannon","Zen Headbutt","Zing Zap","Paleo Wave","Shadow Strike","Magikarp's Revenge"];
const natures = exports.natures = {
	adamant: {name:"Adamant", plus:'atk', minus:'spa'},
	bashful: {name:"Bashful"},
	bold: {name:"Bold", plus:'def', minus:'atk'},
	brave: {name:"Brave", plus:'atk', minus:'spe'},
	calm: {name:"Calm", plus:'spd', minus:'atk'},
	careful: {name:"Careful", plus:'spd', minus:'spa'},
	docile: {name:"Docile"},
	gentle: {name:"Gentle", plus:'spd', minus:'def'},
	hardy: {name:"Hardy"},
	hasty: {name:"Hasty", plus:'spe', minus:'def'},
	impish: {name:"Impish", plus:'def', minus:'spa'},
	jolly: {name:"Jolly", plus:'spe', minus:'spa'},
	lax: {name:"Lax", plus:'def', minus:'spd'},
	lonely: {name:"Lonely", plus:'atk', minus:'def'},
	mild: {name:"Mild", plus:'spa', minus:'def'},
	modest: {name:"Modest", plus:'spa', minus:'atk'},
	naive: {name:"Naive", plus:'spe', minus:'spd'},
	naughty: {name:"Naughty", plus:'atk', minus:'spd'},
	quiet: {name:"Quiet", plus:'spa', minus:'spe'},
	quirky: {name:"Quirky"},
	rash: {name:"Rash", plus:'spa', minus:'spd'},
	relaxed: {name:"Relaxed", plus:'def', minus:'spe'},
	sassy: {name:"Sassy", plus:'spd', minus:'spe'},
	serious: {name:"Serious"},
	timid: {name:"Timid", plus:'spe', minus:'atk'},
};