name: Deploy

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: akhileshns/heroku-deploy@master # This is the action
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "poke-pad"
            heroku_email: ${{secrets.HEROKU_EMAIL}}
